version: '3.8'

volumes:
  pgdata:
  mixdeps:
  elixir_ls:
  mixbuild:

services:
  db:
    image: postgres:16.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: mix phx.server
    env_file:
      - .env
    environment:
      MIX_ENV: "dev"
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - .:/app
      - mixdeps:/app/deps
      - elixir_ls:/app/.elixir_ls
      - mixbuild:/app/_build
